### ISSUE TITLE
WINDSCRIBE_LOCATION - where I can find the List

### ISSUE THREAD

**Issue by RubbeeDuck** [concision/docker-windscribe-socks-server#11]
Hi,

where I can find the List for the WINDSCRIBE_LOCATION ?

Thanks

**Comment by concision** [comment]
Run the container first and Windscribe will automatically select one. Run the following command while the container is running:
```bash
docker exec -it docker-windscribe-socks-server-windscribe-1 windscribe locations
```
Replace `docker-windscribe-socks-server-windscribe-1` with the correct container name obtained from `docker ps`
